name: Build and Publish Docker image
on:
  push:
    branches:
      - test_workflow
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-deep: 0
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Login to GitHub Cotainer Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/$GITHUB_REPOSITORY
      - name: Push image
        run: docker push ghcr.io/$GITHUB_REPOSITORY:latest